version: "3.8"

services:
  auth-api:
    build:
      context: .
    ports:
      - "8090:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
    networks:
      - internal

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: banco-de-reservas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - internal

networks:
  internal:
    driver: bridge
