### Cabeçalhos comuns
@baseUrl = http://localhost:8090
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2FvQGVtYWlsLmNvbSIsImlzcyI6ImF1dGgiLCJleHAiOjE3NDk3NjI1MDF9.iEIxvpwj9vpeDIw2WMifGgGIUu06eQX146zyDsmE-H8
  Content-Type: application/json
Authorization: Bearer {{token}}

### Criar usuário comum
POST {{baseUrl}}/api/usuarios/criar
Content-Type: application/json

{
  "nome": "João",
  "sobrenome": "Silva",
  "email": "joao@email.com",
  "telefone": "11999999999",
  "senha": "SenhaForte@123",
  "dataNascimento": "1990-01-01"
}

###

### Criar usuário administrador
POST {{baseUrl}}/api/usuarios/criar-admin
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Admin",
  "sobrenome": "Master",
  "email": "admin@email.com",
  "telefone": "11988888888",
  "senha": "AdminForte@123",
  "dataNascimento": "1980-05-10"
}

###

### Desativar usuário
PUT {{baseUrl}}/api/usuarios/8b8063df-0405-489e-a207-566e53ffdcdb/desativar
Authorization: Bearer {{token}}

###

### Buscar usuário por ID
GET {{baseUrl}}/api/usuarios/8b8063df-0405-489e-a207-566e53ffdcdb
Authorization: Bearer {{token}}

###

### Listar todos os usuários
GET {{baseUrl}}/api/usuarios/listar-todos
Authorization: Bearer {{token}}


### Atualizar usuário por ID
PUT {{baseUrl}}/api/usuarios/atualizar/60ea0f8e-7a1d-4dc9-b750-ddf018480df6
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nome": "João Atualizado",
  "sobrenome": "Silva Atualizado",
  "telefone": "11987654321",
  "dataNascimento": "1990-05-05"
}