### Cabeçalhos comuns
@baseUrl = http://localhost:8095
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqb2FvQGVtYWlsLmNvbSIsImlzcyI6ImF1dGgiLCJleHAiOjE3NTAyOTY0NjR9.dMoHyZ9Jnszf42uIHNdyswdBVECdNVrpzAdNKJGCgdI
  Content-Type: application/json
Authorization: Bearer {{token}}

### Criar usuário comum
POST {{baseUrl}}/api/usuarios/criar
Content-Type: application/json

{
  "nome": "João",
  "sobrenome": "Silva",
  "email": "joao@email.com",
  "telefone": "11999999999",
  "senha": "SenhaForte@123",
  "dataNascimento": "1990-01-01"
}

###

### Criar usuário administrador
POST {{baseUrl}}/api/usuarios/criar-admin
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "nome": "Admin",
  "sobrenome": "Master",
  "email": "admin@email.com",
  "telefone": "11988888888",
  "senha": "AdminForte@123",
  "dataNascimento": "1980-05-10"
}

###

### Listar todos os usuários
GET {{baseUrl}}/api/usuarios/listar-todos
Authorization: Bearer {{token}}


### Atualizar usuário por ID
PUT {{baseUrl}}/api/usuarios/atualizar/844fb8e3-c7ce-41b2-8e0b-21e00f6d00c6
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nome": "João Atualizado 2",
  "sobrenome": "Silva Atualizado 2",
  "telefone": "11987654323",
  "email": "teste33@gmail.com",
  "dataNascimento": "1990-05-06"
}